import { SceneData } from "./types";

export const DEMO_SCENE_DATA: SceneData = {
  version: "1.0.0",
  name: "Demo Scene",
  metadata: {
    created: Date.now(),
    lastModified: Date.now(),
    author: "Game Studio",
    description: "A demonstration scene showcasing the new architecture",
  },
  cameras: [
    {
      id: "main-camera",
      name: "Main Camera",
      type: "perspective",
      position: [5, 5, 10],
      rotation: [0, 0, 0],
      target: [0, 0, 0],
      active: true,
      properties: {
        fov: 75,
        near: 0.1,
        far: 1000,
      },
      controls: {
        type: "orbit",
        enabled: true,
        properties: {
          enableDamping: true,
          dampingFactor: 0.05,
          minDistance: 2,
          maxDistance: 50,
          autoRotate: false,
        },
      },
    },
  ],
  lighting: {
    ambient: {
      color: 0x404040,
      intensity: 0.4,
    },
    directional: [
      {
        id: "sun-light",
        name: "Sun Light",
        color: 0xffffff,
        intensity: 1.0,
        position: [10, 15, 5],
        castShadow: true,
        shadow: {
          mapSize: [2048, 2048],
          camera: {
            near: 0.1,
            far: 50,
            left: -20,
            right: 20,
            top: 20,
            bottom: -20,
          },
        },
      },
    ],
    point: [
      {
        id: "point-light-1",
        name: "Point Light Blue",
        color: 0x4444ff,
        intensity: 2.0,
        distance: 10,
        decay: 2,
        position: [-5, 3, 0],
        castShadow: false,
      },
      {
        id: "point-light-2",
        name: "Point Light Red",
        color: 0xff4444,
        intensity: 2.0,
        distance: 10,
        decay: 2,
        position: [5, 3, 0],
        castShadow: false,
      },
    ],
    spot: [],
  },
  physics: {
    enabled: true,
    gravity: [0, -9.81, 0],
    debugRender: false,
    solver: {
      iterations: 10,
      timestep: 1 / 60,
    },
  },
  entities: [
    // Ground plane
    {
      id: "ground",
      name: "Ground",
      type: "box",
      position: [0, -1, 0],
      rotation: [0, 0, 0],
      scale: [20, 0.2, 20],
      visible: true,
      castShadow: false,
      receiveShadow: true,
      userData: { purpose: "ground" },
      tags: ["ground", "static"],
      layer: 0,
      physics: {
        enabled: true,
        type: "static",
        restitution: 0.3,
        friction: 0.8,
      },
      geometry: {
        type: "box",
        parameters: {
          width: 20,
          height: 0.2,
          depth: 20,
        },
      },
      material: {
        type: "MeshStandardMaterial",
        properties: {
          color: 0x888888,
          roughness: 0.8,
          metalness: 0.1,
        },
      },
    },
    // Dynamic spheres
    {
      id: "sphere-1",
      name: "Red Sphere",
      type: "sphere",
      position: [-2, 5, 0],
      rotation: [0, 0, 0],
      scale: [1, 1, 1],
      visible: true,
      castShadow: true,
      receiveShadow: true,
      userData: { color: "red" },
      tags: ["dynamic", "sphere"],
      layer: 0,
      physics: {
        enabled: true,
        type: "dynamic",
        mass: 1,
        restitution: 0.7,
        friction: 0.5,
      },
      geometry: {
        type: "sphere",
        parameters: {
          radius: 0.5,
          widthSegments: 32,
          heightSegments: 16,
        },
      },
      material: {
        type: "MeshStandardMaterial",
        properties: {
          color: 0xff4444,
          roughness: 0.4,
          metalness: 0.2,
        },
      },
    },
    {
      id: "sphere-2",
      name: "Blue Sphere",
      type: "sphere",
      position: [2, 6, 0],
      rotation: [0, 0, 0],
      scale: [1, 1, 1],
      visible: true,
      castShadow: true,
      receiveShadow: true,
      userData: { color: "blue" },
      tags: ["dynamic", "sphere"],
      layer: 0,
      physics: {
        enabled: true,
        type: "dynamic",
        mass: 0.8,
        restitution: 0.6,
        friction: 0.5,
      },
      geometry: {
        type: "sphere",
        parameters: {
          radius: 0.4,
          widthSegments: 32,
          heightSegments: 16,
        },
      },
      material: {
        type: "MeshStandardMaterial",
        properties: {
          color: 0x4444ff,
          roughness: 0.3,
          metalness: 0.3,
        },
      },
    },
    // Static boxes
    {
      id: "box-1",
      name: "Platform Box",
      type: "box",
      position: [0, 2, -5],
      rotation: [0, 0, 0],
      scale: [1, 1, 1],
      visible: true,
      castShadow: true,
      receiveShadow: true,
      userData: { purpose: "platform" },
      tags: ["static", "platform"],
      layer: 0,
      physics: {
        enabled: true,
        type: "static",
        restitution: 0.4,
        friction: 0.7,
      },
      geometry: {
        type: "box",
        parameters: {
          width: 3,
          height: 0.5,
          depth: 1,
        },
      },
      material: {
        type: "MeshStandardMaterial",
        properties: {
          color: 0x44ff44,
          roughness: 0.6,
          metalness: 0.1,
        },
      },
    },
    // Torus for variety
    {
      id: "torus-1",
      name: "Golden Torus",
      type: "torus",
      position: [0, 4, 5],
      rotation: [Math.PI / 4, 0, 0],
      scale: [1, 1, 1],
      visible: true,
      castShadow: true,
      receiveShadow: true,
      userData: { material: "gold" },
      tags: ["dynamic", "decorative"],
      layer: 0,
      physics: {
        enabled: true,
        type: "dynamic",
        mass: 2,
        restitution: 0.3,
        friction: 0.8,
      },
      geometry: {
        type: "torus",
        parameters: {
          radius: 1,
          tube: 0.3,
          radialSegments: 16,
          tubularSegments: 50,
        },
      },
      material: {
        type: "MeshStandardMaterial",
        properties: {
          color: 0xffd700,
          roughness: 0.2,
          metalness: 0.8,
        },
      },
    },
  ],
  materials: [],
  textures: [],
}; 